  name: First workflow
  on: [push]
  jobs:
    checkout:
      runs-on: ubuntu-latest
      steps:
        - run: ls
        - uses: actions/checkout/@v4
          with:
            sparse-checkout: .